#spring.datasource.url=jdbc:mariadb://localhost:3306/employee_service
#spring.datasource.username=employee_service
#spring.datasource.password=employee9939
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/securitydcb
    username: securityDCB
    password: securityDCB9939
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
