server:
  port: 9000


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/securitydcb
    username: securityDCB
    password: securityDCB9939
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



